apiVersion: v1
kind: Namespace
metadata:
  name: doit-lab-01-c

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-payload
  namespace: doit-lab-01-c
  labels:
    k8s-app: operator-test
    k8s-scope: gke-ws-doit-lab-01-c
data:
  index.html: Stay Awhile and Listen!
