---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-labeler
  namespace: doit-lab-11
rules:
  - apiGroups: [""] # "" refers to the core API group
    resources: ["pods"]
    verbs: ["list"] # "patch" is intentionally omitted for troubleshooting (see README)
---
# Create a ServiceAccount that will be bound to the role above
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-labeler
  namespace: doit-lab-11
---
# Binds the pod-labeler ServiceAccount to the pod-labeler Role
# Any pod using the pod-labeler ServiceAccount will be granted
# API permissions based on the pod-labeler role.
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-labeler
  namespace: doit-lab-11
subjects:
  # List of service accounts to bind
  - kind: ServiceAccount
    name: pod-labeler
roleRef:
  # The role to bind
  kind: Role
  name: pod-labeler
  apiGroup: rbac.authorization.k8s.io
