#!/bin/bash -eu
#
# Copyright 2021 DoiT International.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# lab preflight lib
#

# -- preflight init process functional group --------------------------------------------------------------------------
preflight() {

    local P_REGION=${1}

    preflight_logo

    if [ "${OPT_NOCHECK}" -eq 1 ]; then
        do_print_msg "preflight checks for this labs deactivated - this can lead to unpredictable results or an incomplete provisioning, we therefore recommend not to use the argument '--no-check'!" "UNSTABLE" 1;
    fi

    preflight_config_check
    preflight_binary_check
    preflight_gcloud_check_sdk "${P_REGION}"
    do_print_line;
}

# -- check config files (json) for this lab ---------------------------------------------------------------------------
preflight_config_check() {

    if [ "${OPT_NOCHECK}" -eq 0 ]; then
        do_check_config_json
        do_print_line
    fi
}

# -- check primary binary scope for this lab --------------------------------------------------------------------------
preflight_binary_check() {

    if [ "${OPT_NOCHECK}" -eq 0 ]; then
        do_check_jq
        do_check_kubectl
        do_check_gsutil
        do_check_gcloud
        do_check_gcloud_auth_status
    fi
}

# -- check primary gcp sdk project link for this lab ------------------------------------------------------------------
preflight_gcloud_check_sdk() {

    local P_REGION=${1}
    if [ "${OPT_NOCHECK}" -eq 0 ]; then
        do_print_line
        do_check_gcloud_status
        do_check_network_status "${P_REGION}"
    fi
}

# -- show logo or some welcome-notes ----------------------------------------------------------------------------------
preflight_logo() {

    if [ "${OPT_QUIET}" -eq 0 ]; then
        do_print_logo
        do_print_line
    fi
}