---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: doit-lab-14
  labels:
    k8s-app: redis
    k8s-scope: gke-ws-doit-lab-14
spec:
  # read more about available storage classes on GKE here:
  # https://cloud.google.com/kubernetes-engine/docs/concepts/persistent-volumes#storageclasses
  storageClassName: premium-rwo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
